# .github/workflows/docker-publish.yml

# Name of the workflow, which will be displayed in the "Actions" tab on GitHub.
name: Docker Publish to GHCR

# This workflow runs on any push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs in this workflow.
env:
  # The container registry to use.
  REGISTRY: ghcr.io
  # The name of the image. We use the GitHub repository name for this.
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
